spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  jpa:
    #open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      #show-sql: true
  redis:
    port:
    host:

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  port:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      #enabled: true
      force-response: true
